### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by berb** [UlmApi/kleinerspatz#1]
The icons are too bright for the map and do not fit the map style.

**Comment by berb** [comment]
Maybe use fontawesome.io for map icons?

**Comment by namnatulco** [comment]
The idea later was to actually go away from the 3x3 types of icons and instead use icons for <3 OR for >3, and not for both, but we haven't implemented this. We could implement that using a dropdown selection (none, >3, <3, both).

**Comment by berb** [comment]
I made the icons a little bit smaller, but they still don't really fit to the map style.

**Comment by stkdiretto** [comment]
trying different icons

//edit: I don't understand the parameters for the info bubble :<

**Comment by namnatulco** [comment]
[this part?](https://github.com/UlmApi/kleinerspatz/blob/cef67467ce4c37f896c3d6c86a06af253d94d240/index.html#L80-L84)
This does:
- create marker at position, with the given icon as marker, and put it on the map
- create a popup string, which is plain HTML that is written to the popup (without actually opening it).

**Comment by stkdiretto** [comment]
Just was made aware that the current icons don't work for people with red/green color blindness.

**Comment by namnatulco** [comment]
And also for those without color blindness, at least me :-).

**Comment by berb** [comment]
OK, icons are super-ugly right now: Low contrast, too dark, badly scaled. I also don't really get the meaning of the cubes given the small size of the icon => revert to the old ones?

**Comment by namnatulco** [comment]
I've created checkbox items as we discussed on Monday. I'll go ahead and try to implement them with layering, s.t. only >3 or <3 can be displayed. I'd use an empty checkbox for no info, checked box for free places, crossed box for no free places. I've stuck to the green/red because I think it looks nicer, but it should be compatible with color-blindness (cross/check).

**Comment by hkopp** [comment]
I think the red lines in the cross could be thicker. I would make them as thick as the green lines in the check.
