### ISSUE TITLE
Improve geo coordinates

### ISSUE THREAD

**Issue by berb** [UlmApi/kleinerspatz#10]
Most items are way off their correct positions. Maybe use geocoding with the addresses to improve results?

**Comment by stkdiretto** [comment]
This might be due to the transformation from GK3 to WGS84. I took the standard Helmert transformation, errors up to 50 meters are common :/

**Comment by stkdiretto** [comment]
Found out the correct parameters due to a similar problem in my thesis. Coordinate precision is within a few metres now.
