### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by berb** [UlmApi/kleinerspatz#11]
Not required for website.

**Comment by namnatulco** [comment]
... but it's helpful for development...?

**Comment by berb** [comment]
IMHO: Nope, because it is confusing, which one represents the current "master". When deploying to GitHub pages, it makes sense to use `gh-pages` like a `master`.

If you develop additional stuff, just use development branches.

**Comment by berb** [comment]
For now, I switched to `gh-pages` as the default branch on this project.
