### ISSUE TITLE
geojson parser broken in python3

### ISSUE THREAD

**Issue by namnatulco** [UlmApi/kleinerspatz#16]
something, probably python3's IPC, seems to break the new parsing script (see geojson branch).

**Comment by danielgeier** [comment]
This seems to be a string<->bytes decoding issue in Python 3. I see no easy way to maintain Python 2 compatibilty here so I suggest we drop support for Python 2.

**Comment by danielgeier** [comment]
Found a simple way that keeps compatibility after all.

**Comment by danielgeier** [comment]
Please do check if everything works for you @namnatulco.
