### ISSUE TITLE
Fix incorrect data set

### ISSUE THREAD

**Issue by berb** [UlmApi/kleinerspatz#7]
Brombeerweg 4,  89075 Ulm != Finningen

**Comment by stkdiretto** [comment]
fixed, although only the wgs84 coordinates are now correct. Nobody is using the GK-coordinates, right? RIGHT?

**Comment by berb** [comment]
Closed by 9c17d78fd6216f83a6cf74c5dc9d9cca40a9bbdf and 7cee426a07229af5bd95be1a21bbbad534ee05cb
